software:
	make -C /home/artiq-alkaline/ARTIQ-alkaline/artiq_kasli/transportable/software/bootloader CPU=vexriscv
	make -C /home/artiq-alkaline/ARTIQ-alkaline/artiq_kasli/transportable/software/libm CPU=vexriscv-g
	make -C /home/artiq-alkaline/ARTIQ-alkaline/artiq_kasli/transportable/software/libprintf CPU=vexriscv-g
	make -C /home/artiq-alkaline/ARTIQ-alkaline/artiq_kasli/transportable/software/libunwind CPU=vexriscv-g
	make -C /home/artiq-alkaline/ARTIQ-alkaline/artiq_kasli/transportable/software/ksupport CPU=vexriscv-g
	make -C /home/artiq-alkaline/ARTIQ-alkaline/artiq_kasli/transportable/software/libunwind CPU=vexriscv
	make -C /home/artiq-alkaline/ARTIQ-alkaline/artiq_kasli/transportable/software/runtime CPU=vexriscv
